# Project information
site_name: Ayaka çŒ«çŒ«ï¼ŒçŒ«çŒ« ğŸ˜¸
site_url: https://bridgel.github.io/ayaka/

# Repository
repo_name: ayaka
repo_url: https://github.com/bridgeL/ayaka/

# Copyright
copyright: Copyright &copy; 2023 - 2023 bridgeL

# dir setting
docs_dir: website
site_dir: docs

# Configuration
theme:
  name: material
  palette:
    primary: teal
    accent: deep orange
  features:
  - content.code.copy
  - content.tabs.link
  - navigation.tabs
  - navigation.indexes
  - navigation.sections
  - navigation.tracking
  - navigation.top
  - navigation.footer
  - toc.integrate
  - search.highlight
  - search.suggest
  hide:
    - toc
nav:
- ä¸»é¡µ: index.md
- å¿«é€Ÿå¼€å§‹: 
  - ç¤ºä¾‹æ’ä»¶: quickstart/example.md
  - ç¢°æ’åŸŸ: quickstart/collision.md
  - æ•°æ®ç¼“å­˜: quickstart/cache.md
- æ·±å…¥: 
  - å±€é™: dev/disable.md
  - å›è°ƒ: dev/on.md
  - å±æ€§: dev/property.md
  - ç¼“å­˜: dev/cache.md
  - é…ç½®: dev/config.md
  - æ•°æ®åº“: dev/database.md
  - è¶…æ—¶: dev/overtime.md
  - è„šæœ¬æµ‹è¯•: dev/test.md
- æ›´æ–°è®°å½•: change-log.md

markdown_extensions:
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- toc:
    title: æœ¬é¡µç´¢å¼•
    permalink: true

plugins:
- search:
    lang:
    - en
    - ja
    separator: '[\s\-\.]+'

extra_javascript:
- js/demo.js
extra_css:
- css/demo.css
