# Project information
site_name: Ayaka çŒ«çŒ«ï¼ŒçŒ«çŒ« ğŸ˜¸
site_url: https://bridgel.github.io/ayaka/

# Repository
repo_name: ayaka
repo_url: https://github.com/bridgeL/ayaka/

# Copyright
copyright: Copyright &copy; 2023 - 2023 bridgeL

# dir setting
docs_dir: website
site_dir: docs

# Configuration
theme:
  name: material
  palette:
    primary: teal
    accent: deep orange
  features:
  - content.code.copy
  - content.tabs.link
  - navigation.tabs
  - navigation.indexes
  - navigation.sections
  - navigation.tracking
  - navigation.top
  - navigation.footer
  - toc.integrate
  - search.highlight
  - search.suggest
  hide:
    - toc
nav:
- ä¸»é¡µ:
  - ä»‹ç»: index.md
  - å®‰è£…: install.md
- å¿«é€Ÿå¼€å§‹: quickstart.md
- æ·±å…¥: 
  - å±€é™: disable.md
  - å›è°ƒ: on.md
  - å±æ€§: property.md
  - ç¼“å­˜: cache.md
  - é…ç½®: config.md
  - æ•°æ®åº“: database.md
  - è„šæœ¬æµ‹è¯•: test.md

markdown_extensions:
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- toc:
    title: æœ¬é¡µç´¢å¼•
    permalink: true

plugins:
- search:
    lang:
    - en
    - ja
    separator: '[\s\-\.]+'

extra_javascript:
- js/demo.js
extra_css:
- css/demo.css
